version: '3'

tasks:
  console:
    desc: Open backend console
    cmds:
      - docker compose exec backend sh
  db:console:
    desc: Open database console
      - docker compose exec postgres psql event_app postgres