version: '3'

tasks:
  default:
    desc: "Run all dev tools at once - formatter, linter"
    cmds:
      - task: format
      - task: lint 
  format:
    desc: Run formatter
    cmds:
      - ruff format
  lint:
    desc: Run linter
    cmds:
      - ruff check --fix
