version: '3'

tasks:
  default:
    desc: "Run all dev tools at once - formatter, linter"
    cmds:
      - task: test
      - task: format
      - task: lint 
      - task: typing
  format:
    desc: Run formatter
    cmds:
      - ruff format
  lint:
    desc: Run linter
    cmds:
      - ruff check --fix
  typing:
    desc: Run type check
    cmds:
      - mypy src --strict
  migrate:
    desc: Run database migrations
    cmds:
      - alembic upgrade head
  test:
    desc: Run mypy tests
    cmds:
      - pytest {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}} tests/ {{end}}
