name: CI Pipline

on: [push]

jobs:
  build:
    name: Setup
    runs-on: ubuntu latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker
        run: docker compose build