name: CI Pipline

on: [push]

jobs:
  build:
    name: Setup
    runs-on: ubuntu latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker
        run: docker compose -f docker-compose.yml build

  checks:
    name: CI checks
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Format
        run: docker compsoe run --rm backend task format